/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlgoRouteImport } from './routes/algo'
import { Route as IndexRouteImport } from './routes/index'

const AlgoRoute = AlgoRouteImport.update({
  id: '/algo',
  path: '/algo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algo': typeof AlgoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algo': typeof AlgoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algo': typeof AlgoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algo'
  id: '__root__' | '/' | '/algo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgoRoute: typeof AlgoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/algo': {
      id: '/algo'
      path: '/algo'
      fullPath: '/algo'
      preLoaderRoute: typeof AlgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgoRoute: AlgoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
